name: 提取boot


on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: ''
jobs:
  YIJIANTIQU:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@main

      - name: 安装依赖
        run: |
         sudo apt-get update
         sudo apt-get -y install python3-pip

      - name: tiqu
        run: |
         pip install git+https://github.com/5ec1cff/payload-dumper
         payload_dumper --partitions init_boot "${{ github.event.inputs.rom_url }}"
